---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
SiteConfig:
  extensions:
    - LddsSiteConfig
#### SHOP CONFIGURATIOn
Email:
  admin_email: heath.dunlop.hd@gmail.com

i18n:
  default_locale: en_NZ

ShopConfig:
  base_currency: 'NZD'
  email_from: sales@myshop.com
  receipt_subject: "Thank you for your order at www.myshop.com - Order #%d"

ShopCurrency:
  decimal_delimiter: '.'
  thousand_delimiter: ','

Product:
  global_allow_purchase: false
  # length_unit: 'M'
  # weight_unit: 'Pounds'

# Change the dimensions of product thumbnails
Product_Image:
  thumbnail_width: 140
  thumbnail_height: 100
  content_image_width: 200
  large_image_width: 200

ProductCategory:
  include_child_groups: true
  must_have_price: true
  sort_options:
    'Title' : 'Alphabetical'
    'Price' : 'Lowest Price'

ShoppingCart_Controller:
  # Redirect to the cart page after manipulating the shopping cart
  direct_to_cart_page: true
  # disable security token for cart-links
  disable_security_token: true

CheckoutConfig:
  member_creation_enabled: false
  membership_required: false

Order:
  modifiers:
    - 'FlatTaxModifier'
    - 'SimpleShippingModifier'
  cancel_before_payment: false
  cancel_before_processing: false
  cancel_before_sending: false
  cancel_before_sending: false
  cancel_after_sending: false
  # Change / add order status, added Refunded
  db:
    Status: Enum('Unpaid,Paid,Processing,Refunded,Sent,Complete,AdminCancelled,MemberCancelled,Cart','Cart')

OrderManipulation:
  allow_cancelling: true
  allow_paying: true


###### PAYMENT CONFIGURATION ######
---
Name: payment
---
Payment:
  file_logging: 1
  allowed_gateways:
    - 'PayPal_Express'
GatewayInfo:
  PayPal_Express:
    parameters:
      username: 'lukedawson66_api1.gmail.com'
      password: 'UT9NB244M5J2GSXP'
      signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31Ak-RhXc3XQzmBzgo6nqMT8h8BmL-'
      testMode: false
#---
#Name: payment
#---
#Payment:
#  file_logging: 1
#  allowed_gateways:
#    - 'PayPal_Express'
#GatewayInfo:
#  PayPal_Express:
#    parameters:
#      username: 'heath.dunlop.hd_api1.gmail.com'
#      password: 'THK6FR66L8NG7Y9J'
#      signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31AnxQkmZfk162mMSxr2moPBia1gQc'
#      testMode: true

#
#PaymentGateway:
#  environment:
#    'live'
#PaymentProcessor:
#  supported_methods:
#    dev:
#      - 'Cheque'
#      - 'PayPalExpress'
#    live:
#      - 'Cheque'
#      - 'PayPalExpress'
#
#PayPalGateway_Express:
#  live:
#    authentication:
#      username: 'lukedawson66_api1.gmail.com'
#      password: 'UT9NB244M5J2GSXP'
#      signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31Ak-RhXc3XQzmBzgo6nqMT8h8BmL-'
#  dev:
#    authentication:
#      username: 'lukedawson66_api1.gmail.com'
#      password: 'UT9NB244M5J2GSXP'
#      signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31Ak-RhXc3XQzmBzgo6nqMT8h8BmL-'