---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
SiteConfig:
  extensions:
    - LddsSiteConfig
PaymentGateway:
  environment:
    'live'
PaymentProcessor:
  supported_methods:
    dev:
      - 'Cheque'
      - 'PayPalExpress'
    live:
      - 'Cheque'
      - 'PayPalExpress'

PayPalGateway_Express:
  live:
    authentication:
      username: 'lukedawson66_api1.gmail.com'
      password: 'UT9NB244M5J2GSXP'
      signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31Ak-RhXc3XQzmBzgo6nqMT8h8BmL-'
  dev:
    authentication:
      username: 'lukedawson66_api1.gmail.com'
      password: 'UT9NB244M5J2GSXP'
      signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31Ak-RhXc3XQzmBzgo6nqMT8h8BmL-'